server:
  port: 0
spring:
  application:
    name: order-query-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
